const lessons = [{
    "date": "September 1, 2019",
    "big_idea": "Jesus is the Messiah",
    "summary": "Jesus reads about the Messiah from Isaiah in the synagogue, and declares the prophecy fulfilled by Him.",
    "scripture": "Luke 4:16-22",
    "scripture_link": "http://oca.org/readings/daily/2019/09/01/6",
    "story_link": "https://www.sstfm.org/luke-4-16-24-puppet-show/",
    "game": "",
    "memorization": "John 1:1",
    "vocabulary": "Messiah - Anointed One",
    "liturgy_highlight": "",
    "coloring_page": "Jesus came to help people",
    "coloring_page_link": "http://ww1.antiochian.org/sites/default/files/2019-09-01-b.pdf",
    "scripture_text": "<dl class=\"reading\"><dt>16</dt><dd>So He came to Nazareth, where He had been brought up. And as His custom was, He went into the synagogue on the Sabbath day, and stood up to read.</dd><dt>17</dt><dd>And He was handed the book of the prophet Isaiah. And when He had opened the book, He found the place where it was written:</dd><dt>18</dt><dd>\"The Spirit of the LORD is upon Me, because He has anointed Me to preach the gospel to the poor; He has sent Me to heal the brokenhearted, to proclaim liberty to the captives and recovery of sight to the blind, to set at liberty those who are oppressed;</dd><dt>19</dt><dd>to proclaim the acceptable year of the LORD.\" </dd><dt>20</dt><dd>Then He closed the book, and gave it back to the attendant and sat down. And the eyes of all who were in the synagogue were fixed on Him.</dd><dt>21</dt><dd>And He began to say to them, \"Today this Scripture is fulfilled in your hearing.\"</dd><dt>22</dt><dd>So all bore witness to Him, and marveled at the gracious words which proceeded out of His mouth. And they said, \"Is this not Joseph's son?\"</dd></dl>",
    "story_format": ["Puppet Show"],
    "songs": ["Numbers", "He's Got The Whole World in His Hands", "Father Abraham (had many sons)"]
}, {
    "date": "September 8, 2019",
    "big_idea": "We all need God",
    "summary": "Jesus showed the man who thought he was perfect that even he had something standing between him and God",
    "scripture": "Matthew 19:16-26",
    "scripture_link": "http://oca.org/readings/daily/2019/09/08/8",
    "story_link": "",
    "game": "",
    "memorization": "John 1:1-2",
    "vocabulary": "Liturgy - from Greek \"leitos\" which means \"people\" and \"ergos\" which means \"work\"",
    "liturgy_highlight": "pages 11 & 13 of Christ Among Us",
    "coloring_page": "WHAT IS REALLY IMPORTANT?",
    "coloring_page_link": "http://ww1.antiochian.org/sites/default/files/2018-08-19-a.pdf",
    "scripture_text": "<dl class=\"reading\"><dt>16</dt><dd>Now behold, one came and said to Him, \"Good Teacher, what good thing shall I do that I may have eternal life?\"</dd><dt>17</dt><dd>So He said to him, \"Why do you call Me good? No one is good but One, that is, God. But if you want to enter into life, keep the commandments.\"</dd><dt>18</dt><dd>He said to Him, \"Which ones?\" Jesus said, \"'You shall not murder,' 'You shall not commit adultery,' 'You shall not steal,' 'You shall not bear false witness,'</dd><dt>19</dt><dd>'Honor your father and your mother,' and, 'You shall love your neighbor as yourself.' \" </dd><dt>20</dt><dd>The young man said to Him, \"All these things I have kept from my youth. What do I still lack?\"</dd><dt>21</dt><dd>Jesus said to him, \"If you want to be perfect, go, sell what you have and give to the poor, and you will have treasure in heaven; and come, follow Me.\"</dd><dt>22</dt><dd>But when the young man heard that saying, he went away sorrowful, for he had great possessions.</dd><dt>23</dt><dd>Then Jesus said to His disciples, \"Assuredly, I say to you that it is hard for a rich man to enter the kingdom of heaven.</dd><dt>24</dt><dd>And again I say to you, it is easier for a camel to go through the eye of a needle than for a rich man to enter the kingdom of God.</dd><dt>25</dt><dd>When His disciples heard it, they were greatly astonished, saying, \"Who then can be saved?\"</dd><dt>26</dt><dd>But Jesus looked at them and said to them, \"With men this is impossible, but with God all things are possible.\"</dd></dl>",
    "story_format": ["Reader Theater"],
    "songs": ["The Wise Man Built His House", "I've Got The Joy, Joy, Joy", "Give Me Oil In My Lamp"]
}, {
    "date": "September 15, 2019",
    "big_idea": "What are you doing with the fruits God has given you?",
    "summary": "A landowner planted a vineyard and hired someone to care for it. When he sent to collect his fruits the landowner refused to give them and instead beat the collectors and killed the landowner's son. The landowner will take away the vineyard and give it to another. You are a vineyard God has planted. What good fruit are you yielding? How do you respond when he asks you to serve him with the fruit you are yielding?",
    "scripture": "Matthew 21:33-42",
    "scripture_link": "https://www.oca.org/readings/daily/2019/09/15/5",
    "story_link": "",
    "game": "",
    "memorization": "John  1:1-3",
    "vocabulary": "Narthex (fellowship area), Nave (where people stand during church)",
    "liturgy_highlight": "Christ  Among Us 15",
    "coloring_page": "WHAT IS MORE IMPORTANT THAN ANYTHING? ",
    "coloring_page_link": "http://ww1.antiochian.org/sites/default/files/2018-08-26-b.pdf",
    "scripture_text": "<dl class=\"reading\"><dt>33</dt><dd>Hear another parable: There was a certain landowner who planted a vineyard and set a hedge around it, dug a winepress in it and built a tower. And he leased it to vinedressers and went into a far country.</dd><dt>34</dt><dd>Now when vintage-time drew near, he sent his servants to the vinedressers, that they might receive its fruit.</dd><dt>35</dt><dd>And the vinedressers took his servants, beat one, killed one, and stoned another.</dd><dt>36</dt><dd>Again he sent other servants, more than the first, and they did likewise to them.</dd><dt>37</dt><dd>Then last of all he sent his son to them, saying, 'They will respect my son.'</dd><dt>38</dt><dd>But when the vinedressers saw the son, they said among themselves, 'This is the heir. Come, let us kill him and seize his inheritance.'</dd><dt>39</dt><dd>So they took him and cast him out of the vineyard and killed him.</dd><dt>40</dt><dd>Therefore, when the owner of the vineyard comes, what will he do to those vinedressers?\"</dd><dt>41</dt><dd>They said to Him, \"He will destroy those wicked men miserably, and lease his vineyard to other vinedressers who will render to him the fruits in their seasons.\"</dd><dt>42</dt><dd>Jesus said to them, \"Have you never read in the Scriptures: 'The stone which the builders rejected Has become the chief cornerstone. This was the LORD's doing, and it is marvelous in our eyes'? </dd></dl>",
    "story_format": ["Flip-pad Drawing"],
    "songs": ["Only a Boy Named David", "Zacchaeus Was a Wee Little Man", "Give Me Oil In My Lamp"]
}, {
    "date": "September 22, 2019",
    "big_idea": "Jesus is worth following",
    "summary": "Jesus told Peter to let down his nets. Peter said had been toiling on his own all night and hadn't caught a thing, but he obeyed and once again let down his net. He caught so much filled both his boat and another until they were sinking. If we are not following God, all that we do is worthless. When we are obeying and following and putting God at the center of our lives, we will bear much good fruit.",
    "scripture": "Luke 5:1-11",
    "scripture_link": "https://www.oca.org/readings/daily/2019/09/22/3",
    "story_link": "",
    "game": "",
    "memorization": "John  1:1-4",
    "vocabulary": "Nave (where people stand during church), Solea - Icon Screen",
    "liturgy_highlight": "16 & the top 2 paragraphs of 17",
    "coloring_page": "JESUS CALLS FISHERMEN ",
    "coloring_page_link": "http://www.antiochian.org/sites/default/files/2018-09-23-a.pdf",
    "scripture_text": "<dl class=\"reading\"><dt>1</dt><dd>So it was, as the multitude pressed about Him to hear the word of God, that He stood by the Lake of Gennesaret,</dd><dt>2</dt><dd>and saw two boats standing by the lake; but the fishermen had gone from them and were washing their nets.</dd><dt>3</dt><dd>Then He got into one of the boats, which was Simon's, and asked him to put out a little from the land. And He sat down and taught the multitudes from the boat.</dd><dt>4</dt><dd>When He had stopped speaking, He said to Simon, \"Launch out into the deep and let down your nets for a catch.\"</dd><dt>5</dt><dd>But Simon answered and said to Him, \"Master, we have toiled all night and caught nothing; nevertheless at Your word I will let down the net.\"</dd><dt>6</dt><dd>And when they had done this, they caught a great number of fish, and their net was breaking.</dd><dt>7</dt><dd>So they signaled to their partners in the other boat to come and help them. And they came and filled both the boats, so that they began to sink.</dd><dt>8</dt><dd>When Simon Peter saw it, he fell down at Jesus' knees, saying, \"Depart from me, for I am a sinful man, O Lord!\"</dd><dt>9</dt><dd>For he and all who were with him were astonished at the catch of fish which they had taken;</dd><dt>10</dt><dd>and so also were James and John, the sons of Zebedee, who were partners with Simon. And Jesus said to Simon, \"Do not be afraid. From now on you will catch men.\"</dd><dt>11</dt><dd>So when they had brought their boats to land, they forsook all and followed Him.</dd></dl>",
    "story_format": ["Felt Board"],
    "songs": ["The Wise Man Built His House", "I've Got The Joy, Joy, Joy", "Arky Arky Noah"]
}, {
    "date": "September 29, 2019",
    "big_idea": "",
    "summary": "",
    "scripture": "Luke 6:31-36",
    "scripture_link": "https://www.oca.org/readings/daily/2019/09/29/3",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "John  1:1-5",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "BE KIND, EVEN WHEN IT'S HARD",
    "coloring_page_link": "http://ww1.antiochian.org/sites/default/files/2018-09-30-a.pdf",
    "scripture_text": "<dl class=\"reading\"><dt>31</dt><dd>And just as you want men to do to you, you also do to them likewise.</dd><dt>32</dt><dd>But if you love those who love you, what credit is that to you? For even sinners love those who love them.</dd><dt>33</dt><dd>And if you do good to those who do good to you, what credit is that to you? For even sinners do the same.</dd><dt>34</dt><dd>And if you lend to those from whom you hope to receive back, what credit is that to you? For even sinners lend to sinners to receive as much back.</dd><dt>35</dt><dd>But love your enemies, do good, and lend, hoping for nothing in return; and your reward will be great, and you will be sons of the Most High. For He is kind to the unthankful and evil.</dd><dt>36</dt><dd>Therefore be merciful, just as your Father also is merciful.</dd></dl>"
}, {
    "date": "October 6, 2019",
    "big_idea": "",
    "summary": "",
    "scripture": "Luke 7:11-16",
    "scripture_link": "https://www.oca.org/readings/daily/2019/10/06/8",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "John  1:1-6",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "JESUS BRINGS A BOY BACK TO LIFE ",
    "coloring_page_link": "http://ww1.antiochian.org/sites/default/files/2018-10-07-a.pdf",
    "scripture_text": "<dl class=\"reading\"><dt>11</dt><dd>Now it happened, the day after, that He went into a city called Nain; and many of His disciples went with Him, and a large crowd.</dd><dt>12</dt><dd>And when He came near the gate of the city, behold, a dead man was being carried out, the only son of his mother; and she was a widow. And a large crowd from the city was with her.</dd><dt>13</dt><dd>When the Lord saw her, He had compassion on her and said to her, \"Do not weep.\"</dd><dt>14</dt><dd>Then He came and touched the open coffin, and those who carried him stood still. And He said, \"Young man, I say to you, arise.\"</dd><dt>15</dt><dd>So he who was dead sat up and began to speak. And He presented him to his mother.</dd><dt>16</dt><dd>Then fear came upon all, and they glorified God, saying, \"A great prophet has risen up among us\"; and, \"God has visited His people.\"</dd></dl>"
}, {
    "date": "October 13, 2019",
    "big_idea": "",
    "summary": "",
    "scripture": "Luke 8:5-15",
    "scripture_link": "https://www.oca.org/readings/daily/2019/10/13/8",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "John  1:1-7",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "THE PARABLE OF THE FARMER",
    "coloring_page_link": "http://ww1.antiochian.org/sites/default/files/2018-10-14-a.pdf",
    "scripture_text": "<dl class=\"reading\"><dt>5</dt><dd>\"A sower went out to sow his seed. And as he sowed, some fell by the wayside; and it was trampled down, and the birds of the air devoured it.</dd><dt>6</dt><dd>Some fell on rock; and as soon as it sprang up, it withered away because it lacked moisture.</dd><dt>7</dt><dd>And some fell among thorns, and the thorns sprang up with it and choked it.</dd><dt>8</dt><dd>But others fell on good ground, sprang up, and yielded a crop a hundredfold.\" When He had said these things He cried, \"He who has ears to hear, let him hear!\"</dd><dt>9</dt><dd>Then His disciples asked Him, saying, \"What does this parable mean?\"</dd><dt>10</dt><dd>And He said, \"To you it has been given to know the mysteries of the kingdom of God, but to the rest it is given in parables, that 'Seeing they may not see, And hearing they may not understand.' </dd><dt>11</dt><dd>Now the parable is this: The seed is the word of God.</dd><dt>12</dt><dd>Those by the wayside are the ones who hear; then the devil comes and takes away the word out of their hearts, lest they should believe and be saved.</dd><dt>13</dt><dd>But the ones on the rock are those who, when they hear, receive the word with joy; and these have no root, who believe for a while and in time of temptation fall away.</dd><dt>14</dt><dd>Now the ones that fell among thorns are those who, when they have heard, go out and are choked with cares, riches, and pleasures of life, and bring no fruit to maturity.</dd><dt>15</dt><dd>But the ones that fell on the good ground are those who, having heard the word with a noble and good heart, keep it and bear fruit with patience.</dd></dl>"
}, {
    "date": "October 20, 2019",
    "big_idea": "",
    "summary": "",
    "scripture": "Luke 16:19-31",
    "scripture_link": "https://www.oca.org/readings/daily/2019/10/20/3",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "John  1:1-8",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "TAKE CARE OF THE POOR",
    "coloring_page_link": "http://ww1.antiochian.org/sites/default/files/2016-10-30-a.pdf",
    "scripture_text": "<dl class=\"reading\"><dt>19</dt><dd>There was a certain rich man who was clothed in purple and fine linen and fared sumptuously every day.</dd><dt>20</dt><dd>But there was a certain beggar named Lazarus, full of sores, who was laid at his gate,</dd><dt>21</dt><dd>desiring to be fed with the crumbs which fell from the rich man's table. Moreover the dogs came and licked his sores.</dd><dt>22</dt><dd>So it was that the beggar died, and was carried by the angels to Abraham's bosom. The rich man also died and was buried.</dd><dt>23</dt><dd>And being in torments in Hades, he lifted up his eyes and saw Abraham afar off, and Lazarus in his bosom.</dd><dt>24</dt><dd>Then he cried and said, 'Father Abraham, have mercy on me, and send Lazarus that he may dip the tip of his finger in water and cool my tongue; for I am tormented in this flame.'</dd><dt>25</dt><dd>But Abraham said, 'Son, remember that in your lifetime you received your good things, and likewise Lazarus evil things; but now he is comforted and you are tormented.</dd><dt>26</dt><dd>And besides all this, between us and you there is a great gulf fixed, so that those who want to pass from here to you cannot, nor can those from there pass to us.'</dd><dt>27</dt><dd>Then he said, 'I beg you therefore, father, that you would send him to my father's house,</dd><dt>28</dt><dd>for I have five brothers, that he may testify to them, lest they also come to this place of torment.'</dd><dt>29</dt><dd>Abraham said to him, 'They have Moses and the prophets; let them hear them.'</dd><dt>30</dt><dd>And he said, 'No, father Abraham; but if one goes to them from the dead, they will repent.'</dd><dt>31</dt><dd>But he said to him, 'If they do not hear Moses and the prophets, neither will they be persuaded though one rise from the dead.'\"</dd></dl>"
}, {
    "date": "October 27, 2019",
    "big_idea": "",
    "summary": "",
    "scripture": "Luke 8:26-39",
    "scripture_link": "https://www.oca.org/readings/daily/2019/10/27/3",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "John  1:1-9",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "JESUS CASTS OUT DEMONS ",
    "coloring_page_link": "http://ww1.antiochian.org/sites/default/files/2018-10-21-a.pdf",
    "scripture_text": "<dl class=\"reading\"><dt>26</dt><dd>Then they sailed to the country of the Gadarenes, which is opposite Galilee.</dd><dt>27</dt><dd>And when He stepped out on the land, there met Him a certain man from the city who had demons for a long time. And he wore no clothes, nor did he live in a house but in the tombs.</dd><dt>28</dt><dd>When he saw Jesus, he cried out, fell down before Him, and with a loud voice said, \"What have I to do with You, Jesus, Son of the Most High God? I beg You, do not torment me!\"</dd><dt>29</dt><dd>For He had commanded the unclean spirit to come out of the man. For it had often seized him, and he was kept under guard, bound with chains and shackles; and he broke the bonds and was driven by the demon into the wilderness.</dd><dt>30</dt><dd>Jesus asked him, saying, \"What is your name?\" And he said, \"Legion,\" because many demons had entered him.</dd><dt>31</dt><dd>And they begged Him that He would not command them to go out into the abyss.</dd><dt>32</dt><dd>Now a herd of many swine was feeding there on the mountain. So they begged Him that He would permit them to enter them. And He permitted them.</dd><dt>33</dt><dd>Then the demons went out of the man and entered the swine, and the herd ran violently down the steep place into the lake and drowned.</dd><dt>34</dt><dd>When those who fed them saw what had happened, they fled and told it in the city and in the country.</dd><dt>35</dt><dd>Then they went out to see what had happened, and came to Jesus, and found the man from whom the demons had departed, sitting at the feet of Jesus, clothed and in his right mind. And they were afraid.</dd><dt>36</dt><dd>They also who had seen it told them by what means he who had been demon-possessed was healed.</dd><dt>37</dt><dd>Then the whole multitude of the surrounding region of the Gadarenes asked Him to depart from them, for they were seized with great fear. And He got into the boat and returned.</dd><dt>38</dt><dd>Now the man from whom the demons had departed begged Him that he might be with Him. But Jesus sent him away, saying,</dd><dt>39</dt><dd>\"Return to your own house, and tell what great things God has done for you.\" And he went his way and proclaimed throughout the whole city what great things Jesus had done for him.</dd></dl>"
}, {
    "date": "November 3, 2019",
    "big_idea": "",
    "summary": "",
    "scripture": "Luke 8:41-56",
    "scripture_link": "https://www.oca.org/readings/daily/2019/11/03/8",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "John  1:1-10",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "",
    "coloring_page_link": "",
    "scripture_text": "<dl class=\"reading\"><dt>41</dt><dd>And behold, there came a man named Jairus, and he was a ruler of the synagogue. And he fell down at Jesus' feet and begged Him to come to his house,</dd><dt>42</dt><dd>for he had an only daughter about twelve years of age, and she was dying. But as He went, the multitudes thronged Him.</dd><dt>43</dt><dd>Now a woman, having a flow of blood for twelve years, who had spent all her livelihood on physicians and could not be healed by any,</dd><dt>44</dt><dd>came from behind and touched the border of His garment. And immediately her flow of blood stopped.</dd><dt>45</dt><dd>And Jesus said, \"Who touched Me?\" When all denied it, Peter and those with him said, \"Master, the multitudes throng and press You, and You say, 'Who touched Me?'\" </dd><dt>46</dt><dd>But Jesus said, \"Somebody touched Me, for I perceived power going out from Me.\"</dd><dt>47</dt><dd>Now when the woman saw that she was not hidden, she came trembling; and falling down before Him, she declared to Him in the presence of all the people the reason she had touched Him and how she was healed immediately.</dd><dt>48</dt><dd>And He said to her, \"Daughter, be of good cheer; your faith has made you well. Go in peace.\"</dd><dt>49</dt><dd>While He was still speaking, someone came from the ruler of the synagogue's house, saying to him, \"Your daughter is dead. Do not trouble the Teacher.\" </dd><dt>50</dt><dd>But when Jesus heard it, He answered him, saying, \"Do not be afraid; only believe, and she will be made well.\"</dd><dt>51</dt><dd>When He came into the house, He permitted no one to go in except Peter, James, and John, and the father and mother of the girl.</dd><dt>52</dt><dd>Now all wept and mourned for her; but He said, \"Do not weep; she is not dead, but sleeping.\"</dd><dt>53</dt><dd>And they ridiculed Him, knowing that she was dead.</dd><dt>54</dt><dd>But He put them all outside, took her by the hand and called, saying, \"Little girl, arise.\"</dd><dt>55</dt><dd>Then her spirit returned, and she arose immediately. And He commanded that she be given something to eat.</dd><dt>56</dt><dd>And her parents were astonished, but He charged them to tell no one what had happened.</dd></dl>"
}, {
    "date": "November 10, 2019",
    "big_idea": "",
    "summary": "",
    "scripture": "Luke 10:25-37",
    "scripture_link": "https://www.oca.org/readings/daily/2019/11/10/3",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "John  1:1-11",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "",
    "coloring_page_link": "",
    "scripture_text": "<dl class=\"reading\"><dt>25</dt><dd>And behold, a certain lawyer stood up and tested Him, saying, \"Teacher, what shall I do to inherit eternal life?\"</dd><dt>26</dt><dd>He said to him, \"What is written in the law? What is your reading of it?\"</dd><dt>27</dt><dd>So he answered and said, \"'You shall love the LORD your God with all your heart, with all your soul, with all your strength, and with all your mind,' and 'your neighbor as yourself.'\" </dd><dt>28</dt><dd>And He said to him, \"You have answered rightly; do this and you will live.\"</dd><dt>29</dt><dd>But he, wanting to justify himself, said to Jesus, \"And who is my neighbor?\"</dd><dt>30</dt><dd>Then Jesus answered and said: \"A certain man went down from Jerusalem to Jericho, and fell among thieves, who stripped him of his clothing, wounded him, and departed, leaving him half dead.</dd><dt>31</dt><dd>Now by chance a certain priest came down that road. And when he saw him, he passed by on the other side.</dd><dt>32</dt><dd>Likewise a Levite, when he arrived at the place, came and looked, and passed by on the other side.</dd><dt>33</dt><dd>But a certain Samaritan, as he journeyed, came where he was. And when he saw him, he had compassion.</dd><dt>34</dt><dd>So he went to him and bandaged his wounds, pouring on oil and wine; and he set him on his own animal, brought him to an inn, and took care of him.</dd><dt>35</dt><dd>On the next day, when he departed, he took out two denarii, gave them to the innkeeper, and said to him, 'Take care of him; and whatever more you spend, when I come again, I will repay you.'</dd><dt>36</dt><dd>So which of these three do you think was neighbor to him who fell among the thieves?\"</dd><dt>37</dt><dd>And he said, \"He who showed mercy on him.\" Then Jesus said to him, \"Go and do likewise.\"</dd></dl>"
}, {
    "date": "November 17, 2019",
    "big_idea": "",
    "summary": "",
    "scripture": "Luke 12:16-21",
    "scripture_link": "https://www.oca.org/readings/daily/2019/11/17/3",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "John  1:1-12",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "",
    "coloring_page_link": "",
    "scripture_text": "<dl class=\"reading\"><dt>16</dt><dd>Then He spoke a parable to them, saying: \"The ground of a certain rich man yielded plentifully.</dd><dt>17</dt><dd>And he thought within himself, saying, 'What shall I do, since I have no room to store my crops?'</dd><dt>18</dt><dd>So he said, 'I will do this: I will pull down my barns and build greater, and there I will store all my crops and my goods.</dd><dt>19</dt><dd>'And I will say to my soul, \"Soul, you have many goods laid up for many years; take your ease; eat, drink, and be merry.\"'</dd><dt>20</dt><dd>But God said to him, 'Fool! This night your soul will be required of you; then whose will those things be which you have provided?'</dd><dt>21</dt><dd>So is he who lays up treasure for himself, and is not rich toward God.\"</dd></dl>"
}, {
    "date": "November 24, 2019",
    "big_idea": "",
    "summary": "",
    "scripture": "Luke 13:10-17",
    "scripture_link": "https://www.oca.org/readings/daily/2019/11/24/3",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "John  1:1-13",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "",
    "coloring_page_link": "",
    "scripture_text": "<dl class=\"reading\"><dt>10</dt><dd>Now He was teaching in one of the synagogues on the Sabbath.</dd><dt>11</dt><dd>And behold, there was a woman who had a spirit of infirmity eighteen years, and was bent over and could in no way raise herself up.</dd><dt>12</dt><dd>But when Jesus saw her, He called her to Him and said to her, \"Woman, you are loosed from your infirmity.\"</dd><dt>13</dt><dd>And He laid His hands on her, and immediately she was made straight, and glorified God.</dd><dt>14</dt><dd>But the ruler of the synagogue answered with indignation, because Jesus had healed on the Sabbath; and he said to the crowd, \"There are six days on which men ought to work; therefore come and be healed on them, and not on the Sabbath day.\"</dd><dt>15</dt><dd>The Lord then answered him and said, \"Hypocrite! Does not each one of you on the Sabbath loose his ox or donkey from the stall, and lead it away to water it?</dd><dt>16</dt><dd>So ought not this woman, being a daughter of Abraham, whom Satan has bound ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¦ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã¢â‚¬Å“ think of it ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Â ÃƒÂ¢Ã¢â€šÂ¬Ã¢â€žÂ¢ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦Ãƒâ€šÃ‚Â¡ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¦ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã¢â‚¬Å“ for eighteen years, be loosed from this bond on the Sabbath?\"</dd><dt>17</dt><dd>And when He said these things, all His adversaries were put to shame; and all the multitude rejoiced for all the glorious things that were done by Him.</dd></dl>"
}, {
    "date": "December 1, 2019",
    "big_idea": "",
    "summary": "",
    "scripture": "Luke 18:18-27",
    "scripture_link": "https://www.oca.org/readings/daily/2019/12/01/3",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "John  1:1-14",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "",
    "coloring_page_link": "",
    "scripture_text": "<dl class=\"reading\"><dt>18</dt><dd>Now a certain ruler asked Him, saying, \"Good Teacher, what shall I do to inherit eternal life?\"</dd><dt>19</dt><dd>So Jesus said to him, \"Why do you call Me good? No one is good but One, that is, God.</dd><dt>20</dt><dd>You know the commandments: 'Do not commit adultery,' 'Do not murder,' 'Do not steal,' 'Do not bear false witness,' 'Honor your father and your mother.'\"</dd><dt>21</dt><dd>And he said, \"All these things I have kept from my youth.\"</dd><dt>22</dt><dd>So when Jesus heard these things, He said to him, \"You still lack one thing. Sell all that you have and distribute to the poor, and you will have treasure in heaven; and come, follow Me.\"</dd><dt>23</dt><dd>But when he heard this, he became very sorrowful, for he was very rich.</dd><dt>24</dt><dd>And when Jesus saw that he became very sorrowful, He said, \"How hard it is for those who have riches to enter the kingdom of God!</dd><dt>25</dt><dd>For it is easier for a camel to go through the eye of a needle than for a rich man to enter the kingdom of God.\"</dd><dt>26</dt><dd>And those who heard it said, \"Who then can be saved?\"</dd><dt>27</dt><dd>But He said, \"The things which are impossible with men are possible with God.\"</dd></dl>"
}, {
    "date": "December 8, 2019",
    "big_idea": "",
    "summary": "",
    "scripture": "Luke 17:12-19",
    "scripture_link": "https://www.oca.org/readings/daily/2019/12/08/3",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "John  1:1-15",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "",
    "coloring_page_link": "",
    "scripture_text": "<dl class=\"reading\"><dt>12</dt><dd>Then as He entered a certain village, there met Him ten men who were lepers, who stood afar off.</dd><dt>13</dt><dd>And they lifted up their voices and said, \"Jesus, Master, have mercy on us!\"</dd><dt>14</dt><dd>So when He saw them, He said to them, \"Go, show yourselves to the priests.\" And so it was that as they went, they were cleansed.</dd><dt>15</dt><dd>And one of them, when he saw that he was healed, returned, and with a loud voice glorified God,</dd><dt>16</dt><dd>and fell down on his face at His feet, giving Him thanks. And he was a Samaritan.</dd><dt>17</dt><dd>So Jesus answered and said, \"Were there not ten cleansed? But where are the nine?</dd><dt>18</dt><dd>Were there not any found who returned to give glory to God except this foreigner?</dd><dt>19</dt><dd>And He said to him, \"Arise, go your way. Your faith has made you well.\"</dd></dl>"
}, {
    "date": "December 15, 2019",
    "big_idea": "",
    "summary": "",
    "scripture": "Luke 14:16-24",
    "scripture_link": "https://www.oca.org/readings/daily/2019/12/15/3",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "John  1:1-16",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "",
    "coloring_page_link": "",
    "scripture_text": "<dl class=\"reading\"><dt>16</dt><dd>Then He said to him, \"A certain man gave a great supper and invited many,</dd><dt>17</dt><dd>and sent his servant at supper time to say to those who were invited, 'Come, for all things are now ready.'</dd><dt>18</dt><dd>But they all with one accord began to make excuses. The first said to him, 'I have bought a piece of ground, and I must go and see it. I ask you to have me excused.'</dd><dt>19</dt><dd>And another said, 'I have bought five yoke of oxen, and I am going to test them. I ask you to have me excused.'</dd><dt>20</dt><dd>Still another said, 'I have married a wife, and therefore I cannot come.'</dd><dt>21</dt><dd>So that servant came and reported these things to his master. Then the master of the house, being angry, said to his servant, 'Go out quickly into the streets and lanes of the city, and bring in here the poor and the maimed and the lame and the blind.'</dd><dt>22</dt><dd>And the servant said, 'Master, it is done as you commanded, and still there is room.'</dd><dt>23</dt><dd>Then the master said to the servant, 'Go out into the highways and hedges, and compel them to come in, that my house may be filled.</dd><dt>24</dt><dd>'For I say to you that none of those men who were invited shall taste my supper.'\"</dd></dl>"
}, {
    "date": "December 22, 2019",
    "big_idea": "",
    "summary": "",
    "scripture": "Matthew 1:1-25",
    "scripture_link": "https://www.oca.org/readings/daily/2019/12/22/6",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "John  1:1-17",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "",
    "coloring_page_link": "",
    "scripture_text": "<dl class=\"reading\"><dt>1</dt><dd>The book of the genealogy of Jesus Christ, the Son of David, the Son of Abraham:</dd><dt>2</dt><dd>Abraham begot Isaac, Isaac begot Jacob, and Jacob begot Judah and his brothers.</dd><dt>3</dt><dd>Judah begot Perez and Zerah by Tamar, Perez begot Hezron, and Hezron begot Ram.</dd><dt>4</dt><dd>Ram begot Amminadab, Amminadab begot Nahshon, and Nahshon begot Salmon.</dd><dt>5</dt><dd>Salmon begot Boaz by Rahab, Boaz begot Obed by Ruth, Obed begot Jesse,</dd><dt>6</dt><dd>and Jesse begot David the king. David the king begot Solomon by her who had been the wife of Uriah.</dd><dt>7</dt><dd>Solomon begot Rehoboam, Rehoboam begot Abijah, and Abijah begot Asa. </dd><dt>8</dt><dd>Asa begot Jehoshaphat, Jehoshaphat begot Joram, and Joram begot Uzziah.</dd><dt>9</dt><dd>Uzziah begot Jotham, Jotham begot Ahaz, and Ahaz begot Hezekiah.</dd><dt>10</dt><dd>Hezekiah begot Manasseh, Manasseh begot Amon, and Amon begot Josiah.</dd><dt>11</dt><dd>Josiah begot Jeconiah and his brothers about the time they were carried away to Babylon.</dd><dt>12</dt><dd>And after they were brought to Babylon, Jeconiah begot Shealtiel, and Shealtiel begot Zerubbabel.</dd><dt>13</dt><dd>Zerubbabel begot Abiud, Abiud begot Eliakim, and Eliakim begot Azor.</dd><dt>14</dt><dd>Azor begot Zadok, Zadok begot Achim, and Achim begot Eliud.</dd><dt>15</dt><dd>Eliud begot Eleazar, Eleazar begot Matthan, and Matthan begot Jacob.</dd><dt>16</dt><dd>And Jacob begot Joseph the husband of Mary, of whom was born Jesus who is called Christ.</dd><dt>17</dt><dd>So all the generations from Abraham to David are fourteen generations, from David until the captivity in Babylon are fourteen generations, and from the captivity in Babylon until the Christ are fourteen generations.</dd><dt>18</dt><dd>Now the birth of Jesus Christ was as follows: After His mother Mary was betrothed to Joseph, before they came together, she was found with child of the Holy Spirit.</dd><dt>19</dt><dd>Then Joseph her husband, being a just man, and not wanting to make her a public example, was minded to put her away secretly.</dd><dt>20</dt><dd>But while he thought about these things, behold, an angel of the Lord appeared to him in a dream, saying, \"Joseph, son of David, do not be afraid to take to you Mary your wife, for that which is conceived in her is of the Holy Spirit.</dd><dt>21</dt><dd>And she will bring forth a Son, and you shall call His name JESUS, for He will save His people from their sins.\"</dd><dt>22</dt><dd>So all this was done that it might be fulfilled which was spoken by the Lord through the prophet, saying:</dd><dt>23</dt><dd>\"Behold, the virgin shall be with child, and bear a Son, and they shall call His name Immanuel, which is translated, 'God with us.'\"</dd><dt>24</dt><dd>Then Joseph, being aroused from sleep, did as the angel of the Lord commanded him and took to him his wife,</dd><dt>25</dt><dd>and did not know her till she had brought forth her firstborn Son. And he called His name JESUS.</dd></dl>"
}, {
    "date": "December 29, 2019",
    "big_idea": "",
    "summary": "",
    "scripture": "Matthew 2:13-23",
    "scripture_link": "https://www.oca.org/readings/daily/2019/12/29/3",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "John  1:1-18",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "",
    "coloring_page_link": "",
    "scripture_text": "<dl class=\"reading\"><dt>13</dt><dd>Now when they had departed, behold, an angel of the Lord appeared to Joseph in a dream, saying, \"Arise, take the young Child and His mother, flee to Egypt, and stay there until I bring you word; for Herod will seek the young Child to destroy Him.\"</dd><dt>14</dt><dd>When he arose, he took the young Child and His mother by night and departed for Egypt,</dd><dt>15</dt><dd>and was there until the death of Herod, that it might be fulfilled which was spoken by the Lord through the prophet, saying, \"Out of Egypt I called My Son.\" </dd><dt>16</dt><dd>Then Herod, when he saw that he was deceived by the wise men, was exceedingly angry; and he sent forth and put to death all the male children who were in Bethlehem and in all its districts, from two years old and under, according to the time which he had determined from the wise men.</dd><dt>17</dt><dd>Then was fulfilled what was spoken by Jeremiah the prophet, saying:</dd><dt>18</dt><dd>\"A voice was heard in Ramah, lamentation, weeping, and great mourning, Rachel weeping for her children, refusing to be comforted, because they are no more.\"</dd><dt>19</dt><dd>Now when Herod was dead, behold, an angel of the Lord appeared in a dream to Joseph in Egypt,</dd><dt>20</dt><dd>saying, \"Arise, take the young Child and His mother, and go to the land of Israel, for those who sought the young Child's life are dead.\"</dd><dt>21</dt><dd>Then he arose, took the young Child and His mother, and came into the land of Israel.</dd><dt>22</dt><dd>But when he heard that Archelaus was reigning over Judea instead of his father Herod, he was afraid to go there. And being warned by God in a dream, he turned aside into the region of Galilee.</dd><dt>23</dt><dd>And he came and dwelt in a city called Nazareth, that it might be fulfilled which was spoken by the prophets, \"He shall be called a Nazarene.\"</dd></dl>"
}, {
    "date": "January 5, 2020",
    "big_idea": "",
    "summary": "",
    "scripture": "Luke 3:1-18",
    "scripture_link": "https://www.oca.org/readings/daily/2020/01/05/18",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "",
    "coloring_page_link": "",
    "scripture_text": "<dl class=\"reading\"><dt>1</dt><dd>Now in the fifteenth year of the reign of Tiberius Caesar, Pontius Pilate being governor of Judea, Herod being tetrarch of Galilee, his brother Philip tetrarch of Iturea and the region of Trachonitis, and Lysanias tetrarch of Abilene,</dd><dt>2</dt><dd>while Annas and Caiaphas were high priests, the word of God came to John the son of Zacharias in the wilderness.</dd><dt>3</dt><dd>And he went into all the region around the Jordan, preaching a baptism of repentance for the remission of sins,</dd><dt>4</dt><dd>as it is written in the book of the words of Isaiah the prophet, saying: \"Prepare the way of the LORD; make His paths straight.</dd><dt>5</dt><dd>Every valley shall be filled and every mountain and hill brought low; the crooked places shall be made straight and the rough ways smooth;</dd><dt>6</dt><dd>and all flesh shall see the salvation of God.\"</dd><dt>7</dt><dd>Then he said to the multitudes that came out to be baptized by him, \"Brood of vipers! Who warned you to flee from the wrath to come?</dd><dt>8</dt><dd>Therefore bear fruits worthy of repentance, and do not begin to say to yourselves, 'We have Abraham as our father.' For I say to you that God is able to raise up children to Abraham from these stones.</dd><dt>9</dt><dd>And even now the ax is laid to the root of the trees. Therefore every tree which does not bear good fruit is cut down and thrown into the fire.\"</dd><dt>10</dt><dd>So the people asked him, saying, \"What shall we do then?\"</dd><dt>11</dt><dd>He answered and said to them, \"He who has two tunics, let him give to him who has none; and he who has food, let him do likewise.\"</dd><dt>12</dt><dd>Then tax collectors also came to be baptized, and said to him, \"Teacher, what shall we do?\"</dd><dt>13</dt><dd>And he said to them, \"Collect no more than what is appointed for you.\"</dd><dt>14</dt><dd>Likewise the soldiers asked him, saying, \"And what shall we do?\" So he said to them, \"Do not intimidate anyone or accuse falsely, and be content with your wages.\"</dd><dt>15</dt><dd>Now as the people were in expectation, and all reasoned in their hearts about John, whether he was the Christ or not,</dd><dt>16</dt><dd>John answered, saying to all, \"I indeed baptize you with water; but One mightier than I is coming, whose sandal strap I am not worthy to loose. He will baptize you with the Holy Spirit and fire.</dd><dt>17</dt><dd>His winnowing fan is in His hand, and He will thoroughly clean out His threshing floor, and gather the wheat into His barn; but the chaff He will burn with unquenchable fire.\"</dd><dt>18</dt><dd>And with many other exhortations he preached to the people.</dd></dl>"
}, {
    "date": "January 12, 2020",
    "big_idea": "",
    "summary": "",
    "scripture": "Matthew 4:12-17",
    "scripture_link": "https://www.oca.org/readings/daily/2020/01/12/3",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "",
    "coloring_page_link": "",
    "scripture_text": "<dl class=\"reading\"><dt>12</dt><dd>Now when Jesus heard that John had been put in prison, He departed to Galilee.</dd><dt>13</dt><dd>And leaving Nazareth, He came and dwelt in Capernaum, which is by the sea, in the regions of Zebulun and Naphtali,</dd><dt>14</dt><dd>that it might be fulfilled which was spoken by Isaiah the prophet, saying:</dd><dt>15</dt><dd>\"The land of Zebulun and the land of Naphtali, by the way of the sea, beyond the Jordan, Galilee of the Gentiles:</dd><dt>16</dt><dd>The people who sat in darkness have seen a great light, and upon those who sat in the region and shadow of death Light has dawned.\" </dd><dt>17</dt><dd>From that time Jesus began to preach and to say, \"Repent, for the kingdom of heaven is at hand.\"</dd></dl>"
}, {
    "date": "January 19, 2020",
    "big_idea": "",
    "summary": "",
    "scripture": "Luke 18:35-43",
    "scripture_link": "https://www.oca.org/readings/daily/2020/01/19/3",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "",
    "coloring_page_link": "",
    "scripture_text": "<dl class=\"reading\"><dt>35</dt><dd>Then it happened, as He was coming near Jericho, that a certain blind man sat by the road begging.</dd><dt>36</dt><dd>And hearing a multitude passing by, he asked what it meant.</dd><dt>37</dt><dd>So they told him that Jesus of Nazareth was passing by.</dd><dt>38</dt><dd>And he cried out, saying, \"Jesus, Son of David, have mercy on me!\"</dd><dt>39</dt><dd>Then those who went before warned him that he should be quiet; but he cried out all the more, \"Son of David, have mercy on me!\"</dd><dt>40</dt><dd>So Jesus stood still and commanded him to be brought to Him. And when he had come near, He asked him,</dd><dt>41</dt><dd>saying, \"What do you want Me to do for you?\" He said, \"Lord, that I may receive my sight.\"</dd><dt>42</dt><dd>Then Jesus said to him, \"Receive your sight; your faith has made you well.\"</dd><dt>43</dt><dd>And immediately he received his sight, and followed Him, glorifying God. And all the people, when they saw it, gave praise to God.</dd></dl>"
}, {
    "date": "January 26, 2020",
    "big_idea": "",
    "summary": "",
    "scripture": "Matthew 15:21-28",
    "scripture_link": "https://www.oca.org/readings/daily/2020/01/26/3",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "",
    "coloring_page_link": "",
    "scripture_text": "<dl class=\"reading\"><dt>21</dt><dd>Then Jesus went out from there and departed to the region of Tyre and Sidon.</dd><dt>22</dt><dd>And behold, a woman of Canaan came from that region and cried out to Him, saying, \"Have mercy on me, O Lord, Son of David! My daughter is severely demon-possessed.\"</dd><dt>23</dt><dd>But He answered her not a word. And His disciples came and urged Him, saying, \"Send her away, for she cries out after us.\"</dd><dt>24</dt><dd>But He answered and said, \"I was not sent except to the lost sheep of the house of Israel.\"</dd><dt>25</dt><dd>Then she came and worshiped Him, saying, \"Lord, help me!\"</dd><dt>26</dt><dd>But He answered and said, \"It is not good to take the children's bread and throw it to the little dogs.\"</dd><dt>27</dt><dd>And she said, \"Yes, Lord, yet even the little dogs eat the crumbs which fall from their masters' table.\"</dd><dt>28</dt><dd>Then Jesus answered and said to her, \"O woman, great is your faith! Let it be to you as you desire.\" And her daughter was healed from that very hour.</dd></dl>"
}, {
    "date": "February 2, 2020",
    "big_idea": "",
    "summary": "",
    "scripture": "Luke 19:1-10 (Gospel)",
    "scripture_link": "https://www.oca.org/readings/daily/2020/02/02/6",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "",
    "coloring_page_link": "",
    "scripture_text": "<dl class=\"reading\"><dt>1</dt><dd>Then Jesus entered and passed through Jericho.</dd><dt>2</dt><dd>Now behold, there was a man named Zacchaeus who was a chief tax collector, and he was rich.</dd><dt>3</dt><dd>And he sought to see who Jesus was, but could not because of the crowd, for he was of short stature.</dd><dt>4</dt><dd>So he ran ahead and climbed up into a sycamore tree to see Him, for He was going to pass that way.</dd><dt>5</dt><dd>And when Jesus came to the place, He looked up and saw him, and said to him, \"Zacchaeus, make haste and come down, for today I must stay at your house.\"</dd><dt>6</dt><dd>So he made haste and came down, and received Him joyfully.</dd><dt>7</dt><dd>But when they saw it, they all complained, saying, \"He has gone to be a guest with a man who is a sinner.\"</dd><dt>8</dt><dd>Then Zacchaeus stood and said to the Lord, \"Look, Lord, I give half of my goods to the poor; and if I have taken anything from anyone by false accusation, I restore fourfold.\"</dd><dt>9</dt><dd>And Jesus said to him, \"Today salvation has come to this house, because he also is a son of Abraham;</dd><dt>10</dt><dd>for the Son of Man has come to seek and to save that which was lost.\"</dd></dl>"
}, {
    "date": "February 9, 2020",
    "big_idea": "",
    "summary": "",
    "scripture": "Luke 18:10-14",
    "scripture_link": "https://www.oca.org/readings/daily/2020/02/09/5",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "",
    "coloring_page_link": "",
    "scripture_text": "<dl class=\"reading\"><dt>10</dt><dd>\"Two men went up to the temple to pray, one a Pharisee and the other a tax collector.</dd><dt>11</dt><dd>The Pharisee stood and prayed thus with himself, 'God, I thank You that I am not like other men ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ extortioners, unjust, adulterers, or even as this tax collector.</dd><dt>12</dt><dd>I fast twice a week; I give tithes of all that I possess.'</dd><dt>13</dt><dd>And the tax collector, standing afar off, would not so much as raise his eyes to heaven, but beat his breast, saying, 'God, be merciful to me a sinner!'</dd><dt>14</dt><dd>I tell you, this man went down to his house justified rather than the other; for everyone who exalts himself will be humbled, and he who humbles himself will be exalted.\"</dd></dl>"
}, {
    "date": "February 16, 2020",
    "big_idea": "",
    "summary": "",
    "scripture": "Luke 15:11-32",
    "scripture_link": "https://www.oca.org/readings/daily/2020/02/16/3",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "",
    "coloring_page_link": "",
    "scripture_text": "<dl class=\"reading\"><dt>11</dt><dd>Then He said: \"A certain man had two sons.</dd><dt>12</dt><dd>And the younger of them said to his father, 'Father, give me the portion of goods that falls to me.' So he divided to them his livelihood.</dd><dt>13</dt><dd>And not many days after, the younger son gathered all together, journeyed to a far country, and there wasted his possessions with prodigal living.</dd><dt>14</dt><dd>But when he had spent all, there arose a severe famine in that land, and he began to be in want.</dd><dt>15</dt><dd>Then he went and joined himself to a citizen of that country, and he sent him into his fields to feed swine.</dd><dt>16</dt><dd>And he would gladly have filled his stomach with the pods that the swine ate, and no one gave him anything.</dd><dt>17</dt><dd>But when he came to himself, he said, 'How many of my father's hired servants have bread enough and to spare, and I perish with hunger!</dd><dt>18</dt><dd>I will arise and go to my father, and will say to him, \"Father, I have sinned against heaven and before you,</dd><dt>19</dt><dd>and I am no longer worthy to be called your son. Make me like one of your hired servants.\"'</dd><dt>20</dt><dd>And he arose and came to his father. But when he was still a great way off, his father saw him and had compassion, and ran and fell on his neck and kissed him.</dd><dt>21</dt><dd>And the son said to him, 'Father, I have sinned against heaven and in your sight, and am no longer worthy to be called your son.'</dd><dt>22</dt><dd>But the father said to his servants, 'Bring out the best robe and put it on him, and put a ring on his hand and sandals on his feet.</dd><dt>23</dt><dd>And bring the fatted calf here and kill it, and let us eat and be merry;</dd><dt>24</dt><dd>for this my son was dead and is alive again; he was lost and is found.' And they began to be merry.</dd><dt>25</dt><dd>Now his older son was in the field. And as he came and drew near to the house, he heard music and dancing.</dd><dt>26</dt><dd>So he called one of the servants and asked what these things meant.</dd><dt>27</dt><dd>And he said to him, 'Your brother has come, and because he has received him safe and sound, your father has killed the fatted calf.'</dd><dt>28</dt><dd>But he was angry and would not go in. Therefore his father came out and pleaded with him.</dd><dt>29</dt><dd>So he answered and said to his father, 'Lo, these many years I have been serving you; I never transgressed your commandment at any time; and yet you never gave me a young goat, that I might make merry with my friends.</dd><dt>30</dt><dd>But as soon as this son of yours came, who has devoured your livelihood with harlots, you killed the fatted calf for him.'</dd><dt>31</dt><dd>And he said to him, 'Son, you are always with me, and all that I have is yours.</dd><dt>32</dt><dd>It was right that we should make merry and be glad, for your brother was dead and is alive again, and was lost and is found.'\"</dd></dl>"
}, {
    "date": "February 23, 2020",
    "big_idea": "",
    "summary": "",
    "scripture": "Matthew 25:31-46",
    "scripture_link": "https://www.oca.org/readings/daily/2020/02/23/3",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "",
    "coloring_page_link": "",
    "scripture_text": "<dl class=\"reading\"><dt>31</dt><dd>When the Son of Man comes in His glory, and all the holy angels with Him, then He will sit on the throne of His glory.</dd><dt>32</dt><dd>All the nations will be gathered before Him, and He will separate them one from another, as a shepherd divides his sheep from the goats.</dd><dt>33</dt><dd>And He will set the sheep on His right hand, but the goats on the left.</dd><dt>34</dt><dd>Then the King will say to those on His right hand, 'Come, you blessed of My Father, inherit the kingdom prepared for you from the foundation of the world:</dd><dt>35</dt><dd>for I was hungry and you gave Me food; I was thirsty and you gave Me drink; I was a stranger and you took Me in;</dd><dt>36</dt><dd>I was naked and you clothed Me; I was sick and you visited Me; I was in prison and you came to Me.'</dd><dt>37</dt><dd>Then the righteous will answer Him, saying, 'Lord, when did we see You hungry and feed You, or thirsty and give You drink?</dd><dt>38</dt><dd>When did we see You a stranger and take You in, or naked and clothe You?</dd><dt>39</dt><dd>Or when did we see You sick, or in prison, and come to You?'</dd><dt>40</dt><dd>And the King will answer and say to them, 'Assuredly, I say to you, inasmuch as you did it to one of the least of these My brethren, you did it to Me.'</dd><dt>41</dt><dd>Then He will also say to those on the left hand, 'Depart from Me, you cursed, into the everlasting fire prepared for the devil and his angels:</dd><dt>42</dt><dd>for I was hungry and you gave Me no food; I was thirsty and you gave Me no drink;</dd><dt>43</dt><dd>I was a stranger and you did not take Me in, naked and you did not clothe Me, sick and in prison and you did not visit Me.'</dd><dt>44</dt><dd>Then they also will answer Him, saying, 'Lord, when did we see You hungry or thirsty or a stranger or naked or sick or in prison, and did not minister to You?'</dd><dt>45</dt><dd>Then He will answer them, saying, 'Assuredly, I say to you, inasmuch as you did not do it to one of the least of these, you did not do it to Me.'</dd><dt>46</dt><dd>And these will go away into everlasting punishment, but the righteous into eternal life.\"</dd></dl>"
}, {
    "date": "March 1, 2020",
    "big_idea": "",
    "summary": "",
    "scripture": "Matthew 6:14-21",
    "scripture_link": "https://www.oca.org/readings/daily/2020/03/01/3",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "",
    "coloring_page_link": "",
    "scripture_text": "<dl class=\"reading\"><dt>14</dt><dd>For if you forgive men their trespasses, your heavenly Father will also forgive you.</dd><dt>15</dt><dd>But if you do not forgive men their trespasses, neither will your Father forgive your trespasses.</dd><dt>16</dt><dd>Moreover, when you fast, do not be like the hypocrites, with a sad countenance. For they disfigure their faces that they may appear to men to be fasting. Assuredly, I say to you, they have their reward.</dd><dt>17</dt><dd>But you, when you fast, anoint your head and wash your face,</dd><dt>18</dt><dd>so that you do not appear to men to be fasting, but to your Father who is in the secret place; and your Father who sees in secret will reward you openly. </dd><dt>19</dt><dd>Do not lay up for yourselves treasures on earth, where moth and rust destroy and where thieves break in and steal;</dd><dt>20</dt><dd>but lay up for yourselves treasures in heaven, where neither moth nor rust destroys and where thieves do not break in and steal.</dd><dt>21</dt><dd>For where your treasure is, there your heart will be also.</dd></dl>"
}, {
    "date": "March 8, 2020",
    "big_idea": "",
    "summary": "",
    "scripture": "John 1:43-51",
    "scripture_link": "https://www.oca.org/readings/daily/2020/03/08/3",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "",
    "coloring_page_link": "",
    "scripture_text": "<dl class=\"reading\"><dt>43</dt><dd>The following day Jesus wanted to go to Galilee, and He found Philip and said to him, \"Follow Me.\"</dd><dt>44</dt><dd>Now Philip was from Bethsaida, the city of Andrew and Peter.</dd><dt>45</dt><dd>Philip found Nathanael and said to him, \"We have found Him of whom Moses in the law, and also the prophets, wrote ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ Jesus of Nazareth, the son of Joseph.\"</dd><dt>46</dt><dd>And Nathanael said to him, \"Can anything good come out of Nazareth?\" Philip said to him, \"Come and see.\"</dd><dt>47</dt><dd>Jesus saw Nathanael coming toward Him, and said of him, \"Behold, an Israelite indeed, in whom is no deceit!\"</dd><dt>48</dt><dd>Nathanael said to Him, \"How do You know me?\" Jesus answered and said to him, \"Before Philip called you, when you were under the fig tree, I saw you.\"</dd><dt>49</dt><dd>Nathanael answered and said to Him, \"Rabbi, You are the Son of God! You are the King of Israel!\"</dd><dt>50</dt><dd>Jesus answered and said to him, \"Because I said to you, 'I saw you under the fig tree,' do you believe? You will see greater things than these.\"</dd><dt>51</dt><dd>And He said to him, \"Most assuredly, I say to you, hereafter you shall see heaven open, and the angels of God ascending and descending upon the Son of Man.\"</dd></dl>"
}, {
    "date": "March 15, 2020",
    "big_idea": "",
    "summary": "",
    "scripture": "Mark 2:1-12",
    "scripture_link": "https://www.oca.org/readings/daily/2020/03/15/5",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "",
    "coloring_page_link": "",
    "scripture_text": "<dl class=\"reading\"><dt>1</dt><dd>And again He entered Capernaum after some days, and it was heard that He was in the house.</dd><dt>2</dt><dd>Immediately many gathered together, so that there was no longer room to receive them, not even near the door. And He preached the word to them.</dd><dt>3</dt><dd>Then they came to Him, bringing a paralytic who was carried by four men.</dd><dt>4</dt><dd>And when they could not come near Him because of the crowd, they uncovered the roof where He was. So when they had broken through, they let down the bed on which the paralytic was lying.</dd><dt>5</dt><dd>When Jesus saw their faith, He said to the paralytic, \"Son, your sins are forgiven you.\"</dd><dt>6</dt><dd>And some of the scribes were sitting there and reasoning in their hearts,</dd><dt>7</dt><dd>\"Why does this Man speak blasphemies like this? Who can forgive sins but God alone?\"</dd><dt>8</dt><dd>But immediately, when Jesus perceived in His spirit that they reasoned thus within themselves, He said to them, \"Why do you reason about these things in your hearts?</dd><dt>9</dt><dd>Which is easier, to say to the paralytic, 'Your sins are forgiven you,' or to say, 'Arise, take up your bed and walk'?</dd><dt>10</dt><dd>But that you may know that the Son of Man has power on earth to forgive sins\" ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ He said to the paralytic,</dd><dt>11</dt><dd>\"I say to you, arise, take up your bed, and go to your house.\"</dd><dt>12</dt><dd>Immediately he arose, took up the bed, and went out in the presence of them all, so that all were amazed and glorified God, saying, \"We never saw anything like this!\"</dd></dl>"
}, {
    "date": "March 22, 2020",
    "big_idea": "",
    "summary": "",
    "scripture": "Mark 8:34-9:1",
    "scripture_link": "https://www.oca.org/readings/daily/2020/03/22/3",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "",
    "coloring_page_link": "",
    "scripture_text": "<dl class=\"reading\"><dt>34</dt><dd>When He had called the people to Himself, with His disciples also, He said to them, \"Whoever desires to come after Me, let him deny himself, and take up his cross, and follow Me.</dd><dt>35</dt><dd>For whoever desires to save his life will lose it, but whoever loses his life for My sake and the gospel's will save it.</dd><dt>36</dt><dd>For what will it profit a man if he gains the whole world, and loses his own soul?</dd><dt>37</dt><dd>Or what will a man give in exchange for his soul?</dd><dt>38</dt><dd>For whoever is ashamed of Me and My words in this adulterous and sinful generation, of him the Son of Man also will be ashamed when He comes in the glory of His Father with the holy angels.\"</dd><dt>1</dt><dd>And He said to them, \"Assuredly, I say to you that there are some standing here who will not taste death till they see the kingdom of God present with power.\"</dd></dl>"
}, {
    "date": "March 29, 2020",
    "big_idea": "",
    "summary": "",
    "scripture": "Mark 9:17-31",
    "scripture_link": "https://www.oca.org/readings/daily/2020/03/29/5",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "",
    "coloring_page_link": "",
    "scripture_text": "<dl class=\"reading\"><dt>17</dt><dd>Then one of the crowd answered and said, \"Teacher, I brought You my son, who has a mute spirit.</dd><dt>18</dt><dd>And wherever it seizes him, it throws him down; he foams at the mouth, gnashes his teeth, and becomes rigid. So I spoke to Your disciples, that they should cast it out, but they could not.\"</dd><dt>19</dt><dd>He answered him and said, \"O faithless generation, how long shall I be with you? How long shall I bear with you? Bring him to Me.\"</dd><dt>20</dt><dd>Then they brought him to Him. And when he saw Him, immediately the spirit convulsed him, and he fell on the ground and wallowed, foaming at the mouth.</dd><dt>21</dt><dd>So He asked his father, \"How long has this been happening to him?\" And he said, \"From childhood.</dd><dt>22</dt><dd>And often he has thrown him both into the fire and into the water to destroy him. But if You can do anything, have compassion on us and help us.\"</dd><dt>23</dt><dd>Jesus said to him, \"If you can believe, all things are possible to him who believes.\"</dd><dt>24</dt><dd>Immediately the father of the child cried out and said with tears, \"Lord, I believe; help my unbelief!\"</dd><dt>25</dt><dd>When Jesus saw that the people came running together, He rebuked the unclean spirit, saying to it: \"Deaf and dumb spirit, I command you, come out of him and enter him no more!\"</dd><dt>26</dt><dd>Then the spirit cried out, convulsed him greatly, and came out of him. And he became as one dead, so that many said, \"He is dead.\"</dd><dt>27</dt><dd>But Jesus took him by the hand and lifted him up, and he arose.</dd><dt>28</dt><dd>And when He had come into the house, His disciples asked Him privately, \"Why could we not cast it out?\"</dd><dt>29</dt><dd>So He said to them, \"This kind can come out by nothing but prayer and fasting.\" </dd><dt>30</dt><dd>Then they departed from there and passed through Galilee, and He did not want anyone to know it.</dd><dt>31</dt><dd>For He taught His disciples and said to them, \"The Son of Man is being betrayed into the hands of men, and they will kill Him. And after He is killed, He will rise the third day.\"</dd></dl>"
}, {
    "date": "April 5, 2020",
    "big_idea": "",
    "summary": "",
    "scripture": "Mark 10:32-45",
    "scripture_link": "https://www.oca.org/readings/daily/2020/04/05/5",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "",
    "coloring_page_link": "",
    "scripture_text": "<dl class=\"reading\"><dt>32</dt><dd>Now they were on the road, going up to Jerusalem, and Jesus was going before them; and they were amazed. And as they followed they were afraid. Then He took the twelve aside again and began to tell them the things that would happen to Him:</dd><dt>33</dt><dd>\"Behold, we are going up to Jerusalem, and the Son of Man will be betrayed to the chief priests and to the scribes; and they will condemn Him to death and deliver Him to the Gentiles;</dd><dt>34</dt><dd>and they will mock Him, and scourge Him, and spit on Him, and kill Him. And the third day He will rise again.\"</dd><dt>35</dt><dd>Then James and John, the sons of Zebedee, came to Him, saying, \"Teacher, we want You to do for us whatever we ask.\"</dd><dt>36</dt><dd>And He said to them, \"What do you want Me to do for you?\"</dd><dt>37</dt><dd>They said to Him, \"Grant us that we may sit, one on Your right hand and the other on Your left, in Your glory.\"</dd><dt>38</dt><dd>But Jesus said to them, \"You do not know what you ask. Are you able to drink the cup that I drink, and be baptized with the baptism that I am baptized with?\"</dd><dt>39</dt><dd>They said to Him, \"We are able.\" So Jesus said to them, \"You will indeed drink the cup that I drink, and with the baptism I am baptized with you will be baptized;</dd><dt>40</dt><dd>but to sit on My right hand and on My left is not Mine to give, but it is for those for whom it is prepared.\"</dd><dt>41</dt><dd>And when the ten heard it, they began to be greatly displeased with James and John.</dd><dt>42</dt><dd>But Jesus called them to Himself and said to them, \"You know that those who are considered rulers over the Gentiles lord it over them, and their great ones exercise authority over them.</dd><dt>43</dt><dd>Yet it shall not be so among you; but whoever desires to become great among you shall be your servant.</dd><dt>44</dt><dd>And whoever of you desires to be first shall be slave of all.</dd><dt>45</dt><dd>For even the Son of Man did not come to be served, but to serve, and to give His life a ransom for many.\"</dd></dl>"
}, {
    "date": "April 12, 2020",
    "big_idea": "",
    "summary": "",
    "scripture": "John 12:1-18",
    "scripture_link": "https://www.oca.org/readings/daily/2020/04/12/6",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "",
    "coloring_page_link": "",
    "scripture_text": "<dl class=\"reading\"><dt>1</dt><dd>Then, six days before the Passover, Jesus came to Bethany, where Lazarus was who had been dead, whom He had raised from the dead.</dd><dt>2</dt><dd>There they made Him a supper; and Martha served, but Lazarus was one of those who sat at the table with Him.</dd><dt>3</dt><dd>Then Mary took a pound of very costly oil of spikenard, anointed the feet of Jesus, and wiped His feet with her hair. And the house was filled with the fragrance of the oil.</dd><dt>4</dt><dd>But one of His disciples, Judas Iscariot, Simon's son, who would betray Him, said,</dd><dt>5</dt><dd>Why was this fragrant oil not sold for three hundred denarii and given to the poor?</dd><dt>6</dt><dd>This he said, not that he cared for the poor, but because he was a thief, and had the money box; and he used to take what was put in it.</dd><dt>7</dt><dd>But Jesus said, \"Let her alone; she has kept this for the day of My burial.</dd><dt>8</dt><dd>For the poor you have with you always, but Me you do not have always.\"</dd><dt>9</dt><dd>Now a great many of the Jews knew that He was there; and they came, not for Jesus' sake only, but that they might also see Lazarus, whom He had raised from the dead.</dd><dt>10</dt><dd>But the chief priests plotted to put Lazarus to death also,</dd><dt>11</dt><dd>because on account of him many of the Jews went away and believed in Jesus.</dd><dt>12</dt><dd>The next day a great multitude that had come to the feast, when they heard that Jesus was coming to Jerusalem,</dd><dt>13</dt><dd>took branches of palm trees and went out to meet Him, and cried out: \"Hosanna! 'Blessed is He who comes in the name of the LORD!' The King of Israel!\"</dd><dt>14</dt><dd>Then Jesus, when He had found a young donkey, sat on it; as it is written:</dd><dt>15</dt><dd>\"Fear not, daughter of Zion; behold, your King is coming, sitting on a donkey's colt.\" </dd><dt>16</dt><dd>His disciples did not understand these things at first; but when Jesus was glorified, then they remembered that these things were written about Him and that they had done these things to Him.</dd><dt>17</dt><dd>Therefore the people, who were with Him when He called Lazarus out of his tomb and raised him from the dead, bore witness.</dd><dt>18</dt><dd>For this reason the people also met Him, because they heard that He had done this sign.</dd></dl>"
}, {
    "date": "April 19, 2020",
    "big_idea": "",
    "summary": "",
    "scripture": "John 1:1-17",
    "scripture_link": "https://www.oca.org/readings/daily/2020/04/19/2",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "",
    "coloring_page_link": "",
    "scripture_text": "<dl class=\"reading\"><dt>1</dt><dd>In the beginning was the Word, and the Word was with God, and the Word was God.</dd><dt>2</dt><dd>He was in the beginning with God.</dd><dt>3</dt><dd>All things were made through Him, and without Him nothing was made that was made.</dd><dt>4</dt><dd>In Him was life, and the life was the light of men.</dd><dt>5</dt><dd>And the light shines in the darkness, and the darkness did not comprehend it.</dd><dt>6</dt><dd>There was a man sent from God, whose name was John.</dd><dt>7</dt><dd>This man came for a witness, to bear witness of the Light, that all through him might believe.</dd><dt>8</dt><dd>He was not that Light, but was sent to bear witness of that Light.</dd><dt>9</dt><dd>That was the true Light which gives light to every man coming into the world. </dd><dt>10</dt><dd>He was in the world, and the world was made through Him, and the world did not know Him.</dd><dt>11</dt><dd>He came to His own, and His own did not receive Him.</dd><dt>12</dt><dd>But as many as received Him, to them He gave the right to become children of God, to those who believe in His name:</dd><dt>13</dt><dd>who were born, not of blood, nor of the will of the flesh, nor of the will of man, but of God.</dd><dt>14</dt><dd>And the Word became flesh and dwelt among us, and we beheld His glory, the glory as of the only begotten of the Father, full of grace and truth.</dd><dt>15</dt><dd>John bore witness of Him and cried out, saying, \"This was He of whom I said, 'He who comes after me is preferred before me, for He was before me.'\"</dd><dt>16</dt><dd>And of His fullness we have all received, and grace for grace.</dd><dt>17</dt><dd>For the law was given through Moses, but grace and truth came through Jesus Christ.</dd></dl>"
}, {
    "date": "April 26, 2020",
    "big_idea": "",
    "summary": "",
    "scripture": "John 20:19-31",
    "scripture_link": "https://www.oca.org/readings/daily/2020/04/26/3",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "",
    "coloring_page_link": "",
    "scripture_text": "<dl class=\"reading\"><dt>19</dt><dd>Then, the same day at evening, being the first day of the week, when the doors were shut where the disciples were assembled, for fear of the Jews, Jesus came and stood in the midst, and said to them, \"Peace be with you.\"</dd><dt>20</dt><dd>When He had said this, He showed them His hands and His side. Then the disciples were glad when they saw the Lord.</dd><dt>21</dt><dd>So Jesus said to them again, \"Peace to you! As the Father has sent Me, I also send you.\"</dd><dt>22</dt><dd>And when He had said this, He breathed on them, and said to them, \"Receive the Holy Spirit.</dd><dt>23</dt><dd>If you forgive the sins of any, they are forgiven them; if you retain the sins of any, they are retained.\"</dd><dt>24</dt><dd>Now Thomas, called the Twin, one of the twelve, was not with them when Jesus came.</dd><dt>25</dt><dd>The other disciples therefore said to him, \"We have seen the Lord.\" So he said to them, \"Unless I see in His hands the print of the nails, and put my finger into the print of the nails, and put my hand into His side, I will not believe.\"</dd><dt>26</dt><dd>And after eight days His disciples were again inside, and Thomas with them. Jesus came, the doors being shut, and stood in the midst, and said, \"Peace to you!\"</dd><dt>27</dt><dd>Then He said to Thomas, \"Reach your finger here, and look at My hands; and reach your hand here, and put it into My side. Do not be unbelieving, but believing.\"</dd><dt>28</dt><dd>And Thomas answered and said to Him, \"My Lord and my God!\"</dd><dt>29</dt><dd>Jesus said to him, \"Thomas, because you have seen Me, you have believed. Blessed are those who have not seen and yet have believed.\"</dd><dt>30</dt><dd>And truly Jesus did many other signs in the presence of His disciples, which are not written in this book;</dd><dt>31</dt><dd>but these are written that you may believe that Jesus is the Christ, the Son of God, and that believing you may have life in His name.</dd></dl>"
}, {
    "date": "May 3, 2020",
    "big_idea": "",
    "summary": "",
    "scripture": "Mark 15:43-16:8",
    "scripture_link": "https://www.oca.org/readings/daily/2020/05/03/8",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "",
    "coloring_page_link": "",
    "scripture_text": "<dl class=\"reading\"><dt>43</dt><dd>Joseph of Arimathea, a prominent council member, who was himself waiting for the kingdom of God, coming and taking courage, went in to Pilate and asked for the body of Jesus.</dd><dt>44</dt><dd>Pilate marveled that He was already dead; and summoning the centurion, he asked him if He had been dead for some time.</dd><dt>45</dt><dd>So when he found out from the centurion, he granted the body to Joseph.</dd><dt>46</dt><dd>Then he bought fine linen, took Him down, and wrapped Him in the linen. And he laid Him in a tomb which had been hewn out of the rock, and rolled a stone against the door of the tomb.</dd><dt>47</dt><dd>And Mary Magdalene and Mary the mother of Joses observed where He was laid.</dd><dt>1</dt><dd>Now when the Sabbath was past, Mary Magdalene, Mary the mother of James, and Salome bought spices, that they might come and anoint Him.</dd><dt>2</dt><dd>Very early in the morning, on the first day of the week, they came to the tomb when the sun had risen.</dd><dt>3</dt><dd>And they said among themselves, \"Who will roll away the stone from the door of the tomb for us?\"</dd><dt>4</dt><dd>But when they looked up, they saw that the stone had been rolled away ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ for it was very large.</dd><dt>5</dt><dd>And entering the tomb, they saw a young man clothed in a long white robe sitting on the right side; and they were alarmed.</dd><dt>6</dt><dd>But he said to them, \"Do not be alarmed. You seek Jesus of Nazareth, who was crucified. He is risen! He is not here. See the place where they laid Him.</dd><dt>7</dt><dd>But go, tell His disciples ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ and Peter ÃƒÆ’Ã†â€™Ãƒâ€ Ã¢â‚¬â„¢ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â‚¬Å¡Ã‚Â¬Ãƒâ€¦Ã‚Â¡ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã†â€™Ãƒâ€šÃ‚Â¢ÃƒÆ’Ã‚Â¢ÃƒÂ¢Ã¢â€šÂ¬Ã…Â¡Ãƒâ€šÃ‚Â¬ÃƒÆ’Ã¢â‚¬Â¦ÃƒÂ¢Ã¢â€šÂ¬Ã…â€œ that He is going before you into Galilee; there you will see Him, as He said to you.\"</dd><dt>8</dt><dd>So they went out quickly and fled from the tomb, for they trembled and were amazed. And they said nothing to anyone, for they were afraid.</dd></dl>"
}, {
    "date": "May 10, 2020",
    "big_idea": "",
    "summary": "",
    "scripture": "John 5:1-15",
    "scripture_link": "https://www.oca.org/readings/daily/2020/05/10/8",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "",
    "coloring_page_link": "",
    "scripture_text": "<dl class=\"reading\"><dt>1</dt><dd>After this there was a feast of the Jews, and Jesus went up to Jerusalem.</dd><dt>2</dt><dd>Now there is in Jerusalem by the Sheep Gate a pool, which is called in Hebrew, Bethesda, having five porches.</dd><dt>3</dt><dd>In these lay a great multitude of sick people, blind, lame, paralyzed, waiting for the moving of the water.</dd><dt>4</dt><dd>For an angel went down at a certain time into the pool and stirred up the water; then whoever stepped in first, after the stirring of the water, was made well of whatever disease he had. </dd><dt>5</dt><dd>Now a certain man was there who had an infirmity thirty-eight years.</dd><dt>6</dt><dd>When Jesus saw him lying there, and knew that he already had been in that condition a long time, He said to him, \"Do you want to be made well?\"</dd><dt>7</dt><dd>The sick man answered Him, \"Sir, I have no man to put me into the pool when the water is stirred up; but while I am coming, another steps down before me.\"</dd><dt>8</dt><dd>Jesus said to him, \"Rise, take up your bed and walk.\"</dd><dt>9</dt><dd>And immediately the man was made well, took up his bed, and walked. And that day was the Sabbath.</dd><dt>10</dt><dd>The Jews therefore said to him who was cured, \"It is the Sabbath; it is not lawful for you to carry your bed.\"</dd><dt>11</dt><dd>He answered them, \"He who made me well said to me, 'Take up your bed and walk.'\"</dd><dt>12</dt><dd>Then they asked him, \"Who is the Man who said to you, 'Take up your bed and walk'?\"</dd><dt>13</dt><dd>But the one who was healed did not know who it was, for Jesus had withdrawn, a multitude being in that place.</dd><dt>14</dt><dd>Afterward Jesus found him in the temple, and said to him, \"See, you have been made well. Sin no more, lest a worse thing come upon you.\"</dd><dt>15</dt><dd>The man departed and told the Jews that it was Jesus who had made him well.</dd></dl>"
}, {
    "date": "May 17, 2020",
    "big_idea": "",
    "summary": "",
    "scripture": "John 4:5-42",
    "scripture_link": "https://www.oca.org/readings/daily/2020/05/17/3",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "",
    "coloring_page_link": "",
    "scripture_text": "<dl class=\"reading\"><dt>5</dt><dd>So He came to a city of Samaria which is called Sychar, near the plot of ground that Jacob gave to his son Joseph.</dd><dt>6</dt><dd>Now Jacob's well was there. Jesus therefore, being wearied from His journey, sat thus by the well. It was about the sixth hour.</dd><dt>7</dt><dd>A woman of Samaria came to draw water. Jesus said to her, \"Give Me a drink.\"</dd><dt>8</dt><dd>For His disciples had gone away into the city to buy food.</dd><dt>9</dt><dd>Then the woman of Samaria said to Him, \"How is it that You, being a Jew, ask a drink from me, a Samaritan woman?\" For Jews have no dealings with Samaritans.</dd><dt>10</dt><dd>Jesus answered and said to her, \"If you knew the gift of God, and who it is who says to you, 'Give Me a drink,' you would have asked Him, and He would have given you living water.\"</dd><dt>11</dt><dd>The woman said to Him, \"Sir, You have nothing to draw with, and the well is deep. Where then do You get that living water?</dd><dt>12</dt><dd>Are You greater than our father Jacob, who gave us the well, and drank from it himself, as well as his sons and his livestock?\"</dd><dt>13</dt><dd>Jesus answered and said to her, \"Whoever drinks of this water will thirst again,</dd><dt>14</dt><dd>but whoever drinks of the water that I shall give him will never thirst. But the water that I shall give him will become in him a fountain of water springing up into everlasting life.\"</dd><dt>15</dt><dd>The woman said to Him, \"Sir, give me this water, that I may not thirst, nor come here to draw.\"</dd><dt>16</dt><dd>Jesus said to her, \"Go, call your husband, and come here.\"</dd><dt>17</dt><dd>The woman answered and said, \"I have no husband.\" Jesus said to her, \"You have well said, 'I have no husband,'</dd><dt>18</dt><dd>for you have had five husbands, and the one whom you now have is not your husband; in that you spoke truly.\"</dd><dt>19</dt><dd>The woman said to Him, \"Sir, I perceive that You are a prophet.</dd><dt>20</dt><dd>Our fathers worshiped on this mountain, and you Jews say that in Jerusalem is the place where one ought to worship.\"</dd><dt>21</dt><dd>Jesus said to her, \"Woman, believe Me, the hour is coming when you will neither on this mountain, nor in Jerusalem, worship the Father.</dd><dt>22</dt><dd>You worship what you do not know; we know what we worship, for salvation is of the Jews.</dd><dt>23</dt><dd>But the hour is coming, and now is, when the true worshipers will worship the Father in spirit and truth; for the Father is seeking such to worship Him.</dd><dt>24</dt><dd>God is Spirit, and those who worship Him must worship in spirit and truth.\"</dd><dt>25</dt><dd>The woman said to Him, \"I know that Messiah is coming\" (who is called Christ). \"When He comes, He will tell us all things.\"</dd><dt>26</dt><dd>Jesus said to her, \"I who speak to you am He.\"</dd><dt>27</dt><dd>And at this point His disciples came, and they marveled that He talked with a woman; yet no one said, \"What do You seek?\" or, \"Why are You talking with her?\"</dd><dt>28</dt><dd>The woman then left her waterpot, went her way into the city, and said to the men,</dd><dt>29</dt><dd>Come, see a Man who told me all things that I ever did. Could this be the Christ?</dd><dt>30</dt><dd>Then they went out of the city and came to Him.</dd><dt>31</dt><dd>In the meantime His disciples urged Him, saying, \"Rabbi, eat.\"</dd><dt>32</dt><dd>But He said to them, \"I have food to eat of which you do not know.\"</dd><dt>33</dt><dd>Therefore the disciples said to one another, \"Has anyone brought Him anything to eat?\"</dd><dt>34</dt><dd>Jesus said to them, \"My food is to do the will of Him who sent Me, and to finish His work.</dd><dt>35</dt><dd>Do you not say, 'There are still four months and then comes the harvest'? Behold, I say to you, lift up your eyes and look at the fields, for they are already white for harvest!</dd><dt>36</dt><dd>And he who reaps receives wages, and gathers fruit for eternal life, that both he who sows and he who reaps may rejoice together.</dd><dt>37</dt><dd>For in this the saying is true: 'One sows and another reaps.'</dd><dt>38</dt><dd>I sent you to reap that for which you have not labored; others have labored, and you have entered into their labors.\"</dd><dt>39</dt><dd>And many of the Samaritans of that city believed in Him because of the word of the woman who testified, \"He told me all that I ever did.\"</dd><dt>40</dt><dd>So when the Samaritans had come to Him, they urged Him to stay with them; and He stayed there two days.</dd><dt>41</dt><dd>And many more believed because of His own word.</dd><dt>42</dt><dd>Then they said to the woman, \"Now we believe, not because of what you said, for we ourselves have heard Him and we know that this is indeed the Christ, the Savior of the world.\"</dd></dl>"
}, {
    "date": "May 24, 2020",
    "big_idea": "",
    "summary": "",
    "scripture": "John 9:1-38",
    "scripture_link": "https://www.oca.org/readings/daily/2020/05/24/3",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "",
    "coloring_page_link": "",
    "scripture_text": "<dl class=\"reading\"><dt>1</dt><dd>Now as Jesus passed by, He saw a man who was blind from birth.</dd><dt>2</dt><dd>And His disciples asked Him, saying, \"Rabbi, who sinned, this man or his parents, that he was born blind?\"</dd><dt>3</dt><dd>Jesus answered, \"Neither this man nor his parents sinned, but that the works of God should be revealed in him.</dd><dt>4</dt><dd>I must work the works of Him who sent Me while it is day; the night is coming when no one can work.</dd><dt>5</dt><dd>As long as I am in the world, I am the light of the world.\"</dd><dt>6</dt><dd>When He had said these things, He spat on the ground and made clay with the saliva; and He anointed the eyes of the blind man with the clay.</dd><dt>7</dt><dd>And He said to him, \"Go, wash in the pool of Siloam\" (which is translated, Sent). So he went and washed, and came back seeing.</dd><dt>8</dt><dd>Therefore the neighbors and those who previously had seen that he was blind said, \"Is not this he who sat and begged?\"</dd><dt>9</dt><dd>Some said, \"This is he.\" Others said, \"He is like him.\" He said, \"I am he.\"</dd><dt>10</dt><dd>Therefore they said to him, \"How were your eyes opened?\"</dd><dt>11</dt><dd>He answered and said, \"A Man called Jesus made clay and anointed my eyes and said to me, 'Go to the pool of Siloam and wash.' So I went and washed, and I received sight.\"</dd><dt>12</dt><dd>Then they said to him, \"Where is He?\" He said, \"I do not know.\"</dd><dt>13</dt><dd>They brought him who formerly was blind to the Pharisees.</dd><dt>14</dt><dd>Now it was a Sabbath when Jesus made the clay and opened his eyes.</dd><dt>15</dt><dd>Then the Pharisees also asked him again how he had received his sight. He said to them, \"He put clay on my eyes, and I washed, and I see.\"</dd><dt>16</dt><dd>Therefore some of the Pharisees said, \"This Man is not from God, because He does not keep the Sabbath.\" Others said, \"How can a man who is a sinner do such signs?\" And there was a division among them.</dd><dt>17</dt><dd>They said to the blind man again, \"What do you say about Him because He opened your eyes?\" He said, \"He is a prophet.\"</dd><dt>18</dt><dd>But the Jews did not believe concerning him, that he had been blind and received his sight, until they called the parents of him who had received his sight.</dd><dt>19</dt><dd>And they asked them, saying, \"Is this your son, who you say was born blind? How then does he now see?\"</dd><dt>20</dt><dd>His parents answered them and said, \"We know that this is our son, and that he was born blind;</dd><dt>21</dt><dd>but by what means he now sees we do not know, or who opened his eyes we do not know. He is of age; ask him. He will speak for himself.\"</dd><dt>22</dt><dd>His parents said these things because they feared the Jews, for the Jews had agreed already that if anyone confessed that He was Christ, he would be put out of the synagogue.</dd><dt>23</dt><dd>Therefore his parents said, \"He is of age; ask him.\"</dd><dt>24</dt><dd>So they again called the man who was blind, and said to him, \"Give God the glory! We know that this Man is a sinner.\"</dd><dt>25</dt><dd>He answered and said, \"Whether He is a sinner or not I do not know. One thing I know: that though I was blind, now I see.\"</dd><dt>26</dt><dd>Then they said to him again, \"What did He do to you? How did He open your eyes?\"</dd><dt>27</dt><dd>He answered them, \"I told you already, and you did not listen. Why do you want to hear it again? Do you also want to become His disciples?\"</dd><dt>28</dt><dd>Then they reviled him and said, \"You are His disciple, but we are Moses' disciples.</dd><dt>29</dt><dd>We know that God spoke to Moses; as for this fellow, we do not know where He is from.\"</dd><dt>30</dt><dd>The man answered and said to them, \"Why, this is a marvelous thing, that you do not know where He is from; yet He has opened my eyes!</dd><dt>31</dt><dd>Now we know that God does not hear sinners; but if anyone is a worshiper of God and does His will, He hears him.</dd><dt>32</dt><dd>Since the world began it has been unheard of that anyone opened the eyes of one who was born blind.</dd><dt>33</dt><dd>If this Man were not from God, He could do nothing.\"</dd><dt>34</dt><dd>They answered and said to him, \"You were completely born in sins, and are you teaching us?\" And they cast him out.</dd><dt>35</dt><dd>Jesus heard that they had cast him out; and when He had found him, He said to him, \"Do you believe in the Son of God?\" </dd><dt>36</dt><dd>He answered and said, \"Who is He, Lord, that I may believe in Him?\"</dd><dt>37</dt><dd>And Jesus said to him, \"You have both seen Him and it is He who is talking with you.\"</dd><dt>38</dt><dd>Then he said, \"Lord, I believe!\" And he worshiped Him.</dd></dl>"
}, {
    "date": "May 31, 2020",
    "big_idea": "",
    "summary": "",
    "scripture": "John 17:1-13",
    "scripture_link": "https://www.oca.org/readings/daily/2020/05/31/6",
    "story_format": "",
    "story_link": "",
    "songs": "",
    "game": "",
    "memorization": "",
    "vocabulary": "",
    "liturgy_highlight": "",
    "coloring_page": "",
    "coloring_page_link": "",
    "scripture_text": "<dl class=\"reading\"><dt>1</dt><dd>Jesus spoke these words, lifted up His eyes to heaven, and said: \"Father, the hour has come. Glorify Your Son, that Your Son also may glorify You,</dd><dt>2</dt><dd>as You have given Him authority over all flesh, that He should give eternal life to as many as You have given Him.</dd><dt>3</dt><dd>And this is eternal life, that they may know You, the only true God, and Jesus Christ whom You have sent.</dd><dt>4</dt><dd>I have glorified You on the earth. I have finished the work which You have given Me to do.</dd><dt>5</dt><dd>And now, O Father, glorify Me together with Yourself, with the glory which I had with You before the world was.</dd><dt>6</dt><dd>I have manifested Your name to the men whom You have given Me out of the world. They were Yours, You gave them to Me, and they have kept Your word.</dd><dt>7</dt><dd>Now they have known that all things which You have given Me are from You.</dd><dt>8</dt><dd>For I have given to them the words which You have given Me; and they have received them, and have known surely that I came forth from You; and they have believed that You sent Me.</dd><dt>9</dt><dd>I pray for them. I do not pray for the world but for those whom You have given Me, for they are Yours.</dd><dt>10</dt><dd>And all Mine are Yours, and Yours are Mine, and I am glorified in them.</dd><dt>11</dt><dd>Now I am no longer in the world, but these are in the world, and I come to You. Holy Father, keep through Your name those whom You have given Me, that they may be one as We are.</dd><dt>12</dt><dd>While I was with them in the world, I kept them in Your name. Those whom You gave Me I have kept; and none of them is lost except the son of perdition, that the Scripture might be fulfilled.</dd><dt>13</dt><dd>But now I come to You, and these things I speak in the world, that they may have My joy fulfilled in themselves.</dd></dl>"
}]